migrate to <random>
rand/srand were probably already deprecated by the time this code was written...
I took the error on MoveIt's CI as an incentive to migrate to std::random:

As example code referred to a seeding step, I added an explicit setRandomSeed to the API.

<<<
rviz_visual_tools.cpp:2810:42: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
  float d = static_cast<float>(rand()) / RAND_MAX;
                                       ~ ^~~~~~~~
/usr/include/stdlib.h:86:18: note: expanded from macro 'RAND_MAX'
                          ^~~~~~~~~~
<<<